In [1]:
from numpy import array, ndarray, ones, kron
"""处理self_pos的实验"""
self_pos = array(
    [[[1],
      [2],
      [1]],
     [[0],
      [1],
      [2]]]
)
l = ones((1,1,3))
print(kron(self_pos,l))

[[[1. 1. 1.]
  [2. 2. 2.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [2. 2. 2.]]]


In [2]:
from Rule import Gravity, _test_Gravity
from numpy import array
import numpy as np
Ms = array(
    [[[1,1]],
     [[2,1]],
     [[2,1]]]
) * 1e10

self_pos = array(
    [[[1],
      [2],
      [1]],
     [[0],
      [0],
      [0]],
     [[1],
      [0],
      [1]]
    ]
)
pos = array(
    [[[0,1],
      [0,0],
      [0,1]],
     [[1,1],
      [2,0],
      [1,1]],
     [[1,0],
      [2,0],
      [1,0]]]
)
M = array([2,1,1])*1e10
# 计算对第一个星球的引力加速度
acc10,acc01 = _test_Gravity(M[0],M[1],self_pos[0],self_pos[1])
acc20,acc02 = _test_Gravity(M[0],M[2],self_pos[0],self_pos[2])
ans = Gravity(Ms,pos,self_pos,debug=True)
print(acc10)
print(acc20)
"""测试Gravity函数，成功！！！"""
print(ans)

delts_pos:
 [[[-1.  0.]
  [-2. -2.]
  [-1.  0.]]

 [[ 1.  1.]
  [ 2.  0.]
  [ 1.  1.]]

 [[ 0. -1.]
  [ 2.  0.]
  [ 0. -1.]]]
Rs:
 [[[2.44948974 2.        ]]

 [[2.44948974 1.41421356]]

 [[2.         1.41421356]]]
Ms:
 [[[1.e+10 1.e+10]]

 [[2.e+10 1.e+10]]

 [[2.e+10 1.e+10]]]
Rs**3:
 [[[14.69693846  8.        ]]

 [[14.69693846  2.82842712]]

 [[ 8.          2.82842712]]]
G * Ms / Rs**3:
 [[[0.04541082 0.083425  ]]

 [[0.09082164 0.23596153]]

 [[0.16685    0.23596153]]]
delts_pos:
 [[[-1.  0.]
  [-2. -2.]
  [-1.  0.]]

 [[ 1.  1.]
  [ 2.  0.]
  [ 1.  1.]]

 [[ 0. -1.]
  [ 2.  0.]
  [ 0. -1.]]]
tmp_acc:
 [[[-0.04541082  0.        ]
  [-0.09082164 -0.16685   ]
  [-0.04541082  0.        ]]

 [[ 0.09082164  0.23596153]
  [ 0.18164327  0.        ]
  [ 0.09082164  0.23596153]]

 [[ 0.         -0.23596153]
  [ 0.3337      0.        ]
  [ 0.         -0.23596153]]]
[[-0.04541082]
 [-0.09082164]
 [-0.04541082]]
[[ 0.     ]
 [-0.16685]
 [ 0.     ]]
[[[-0.04541082]
  [-0.25767164]
  [-0.045410

In [3]:
from numpy import array
M1 = array([1,2,3,4]).reshape(1,1,-1)
M2 = array([5,6,7,8]).reshape(1,1,-1)
M = np.concatenate((M1,M2),axis=0)
print(M)

pos1 = array(
    [[[1],
      [2],
      [1]],
     [[0],
      [9],
      [0]],
     [[1],
      [0],
      [1]],
     [[4],
      [9],
      [0]]]
)
from Item import generate_hub
M_hub,pos_hub = generate_hub(M1,pos1)
print(M_hub.shape)
print(M_hub)
print(pos_hub.shape)
print(pos_hub)

[[[1 2 3 4]]

 [[5 6 7 8]]]
(4, 1, 3)
[[[2 3 4]]

 [[1 3 4]]

 [[1 2 4]]

 [[1 2 3]]]
(4, 3, 3)
[[[0 1 4]
  [9 0 9]
  [0 1 0]]

 [[1 1 4]
  [2 0 9]
  [1 1 0]]

 [[1 0 4]
  [2 9 9]
  [1 0 0]]

 [[1 0 1]
  [2 9 0]
  [1 0 1]]]


In [5]:
"""测试System类"""
from Item import System, Star
from numpy import array
import numpy as np
star1 = Star(
    pos=array([0,0,0]),
    radius=3,
    color=(0,1,0),
    vel=array([0,0,0]),
)
star2 = Star(
    pos=array([1,0,0]),
    radius=3,
    color=(0,0,1),
    vel=array([0,0,0]),
)
system = System([star1,star2])
print(system)
print(system.pos)
print(system.pos_hub)
for i in range(100):
    system.update(0.1)
print(system)

System(
M:
[1.13097336e+10 1.13097336e+10],
pos:
[[[0.]
  [0.]
  [0.]]

 [[1.]
  [0.]
  [0.]]]
)
[[[0.]
  [0.]
  [0.]]

 [[1.]
  [0.]
  [0.]]]
[[[1.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
System(
M:
[1.13097336e+10 1.13097336e+10],
pos:
[[[ 12.28706136]
  [  0.        ]
  [  0.        ]]

 [[-11.28706136]
  [  0.        ]
  [  0.        ]]]
)


In [1]:
from Item import convert_to_plot
import numpy as np
self_pos = np.array(
    [[[1],
      [2],
      [1]],
     [[0],
      [1],
      [2]]]
)
print(convert_to_plot(self_pos))

[[1 0]
 [2 1]
 [1 2]]


In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('solar_system_data.csv')
df['位置'] = df['位置'].apply(lambda x: np.fromstring(x.strip('[]'), sep=' ') if pd.notna(x) else None)
df['速度'] = df['速度'].apply(lambda x: np.fromstring(x.strip('[]'), sep=' ') if pd.notna(x) else None)
li = df.to_dict(orient='records')


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
